[workspace]
members = [
    "crates/bridgepad-daemon",
    "crates/bridgepad-bluetooth-spike",
    "crates/bridgepad-desktop",
    "crates/bridgepad-gamepad-spike",
    "crates/bridgepad-protocol",
    "crates/bridgepad-transport-spike",
    "crates/bridgepad-usb-spike",
    "crates/bridgepad-virtual-device",
    "crates/bridgepad-windows-vigem",
    "crates/bridgepad-windows-pointer",
]
default-members = [
    "crates/bridgepad-daemon",
    "crates/bridgepad-bluetooth-spike",
    "crates/bridgepad-gamepad-spike",
    "crates/bridgepad-protocol",
    "crates/bridgepad-transport-spike",
    "crates/bridgepad-usb-spike",
    "crates/bridgepad-virtual-device",
    "crates/bridgepad-windows-vigem",
    "crates/bridgepad-windows-pointer",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "MIT"
repository = "https://github.com/DuarteFrugoli/bridgepad"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
